version: '3.7'
services:
  api:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    container_name: api
  client:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: client
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: db

